HW1
D1m0000n/smart-home-2021 pull request #1
Opened 2021-03-10 18:05 UTC by D1m0000n

2021-03-16 05:41 UTC, a-ivanov requested changes

2021-03-16 05:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        while (event != null) {
SRP: отдельная ответственность, в отдельный класс.

2021-03-16 05:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        SensorEventCreatorImpl sensorEventCreator = new SensorEventCreatorImpl();
Эти зависимости можно создать в `main` и передать классу с циклом через конструктор.

2021-03-16 05:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventProcessor.java
> +            sensorEventHandler = new LightSensorEventHandler(smartHome.getRooms(), event);
DIP: создайте зависимости в `main` и передавайте сюда через конструктор.

2021-03-16 05:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventProcessor.java
> +        if (event.getType() == LIGHT_ON || event.getType() == LIGHT_OFF) {
OCP: перепишите так, чтобы можно было добавлять новые обработчики без изменения кода этого класса.

2021-03-16 05:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/readers/JSONSmartHomeReader.java
> +    public SmartHome readSmartHome() {
У вас в методе интерфейса есть `ioexception`, уберите его. В абстракции не должно быть деталей реализации (мы можем читать из другого источника).

2021-03-16 05:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/DoorSensorEventHandler.java
> +        if (room.getName().equals("hall")) {
SRP: отдельная ответственность для обработки сценария.

2021-03-16 05:41 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/DoorSensorEventHandler.java
> +    private final Collection<Room> rooms;
Нет, мы не разбираем дом на части. Дом ответственен за состояние дверей, поэтому лучше не давать ссылки другим классам.

2021-03-16 18:51 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/readers/JSONSmartHomeReader.java
> +    public SmartHome readSmartHome() {
Исправил

2021-03-16 18:56 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/DoorSensorEventHandler.java
> +        if (room.getName().equals("hall")) {
Исправил

2021-03-16 18:59 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/DoorSensorEventHandler.java
> +    private final Collection<Room> rooms;
Исправил

2021-03-16 19:07 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/EventProcessor.java
> +        if (event.getType() == LIGHT_ON || event.getType() == LIGHT_OFF) {
Исправил

2021-03-16 19:11 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        while (event != null) {
Исправил

2021-03-16 19:13 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/Application.java
> +        SensorEventCreatorImpl sensorEventCreator = new SensorEventCreatorImpl();
Исправил

2021-03-16 19:14 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/EventProcessor.java
> +            sensorEventHandler = new LightSensorEventHandler(smartHome.getRooms(), event);
Исправил

2021-03-17 05:43 UTC, a-ivanov requested changes

2021-03-17 05:43 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventLoopProcessor.java
> +        EventProcessor eventProcessor = new EventProcessor(smartHome);
DIP: создайте в `main`.

2021-03-17 05:43 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SensorEventQualifier.java
> +        if (event.getType() == LIGHT_ON || event.getType() == LIGHT_OFF) {
Не исправлено. Ещё раз, тут нарушены OCP, DIP. См. комментарий из предыдущих исправлений.
И вообще Qualifier выглядит лишним, всю эту работу по делегации обработки можно делать в Processor.

2021-03-17 05:43 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/DoorSensorEventHandler.java
> +    private final Collection<Room> rooms;
Так ведь не исправили) Поле rooms так и осталось на месте. Передайте сюда дом, забирайте комнаты из него. В дз 2 мы и этот момент улучшим.

2021-03-17 16:24 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/DoorSensorEventHandler.java
> +    private final Collection<Room> rooms;
Я уже просто приступил к выполнению 2го дз, где это исправление было применено

2021-03-17 16:27 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/EventLoopProcessor.java
> +        EventProcessor eventProcessor = new EventProcessor(smartHome);
Данное исправление для удобства тоже будет исправлено вместе со второрым домашним заданием

2021-03-17 18:56 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/SensorEventQualifier.java
> +        if (event.getType() == LIGHT_ON || event.getType() == LIGHT_OFF) {
Исправил во второй домашке, избавившись от Qualifier

2021-03-18 05:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventLoopProcessor.java
> +        EventProcessor eventProcessor = new EventProcessor(smartHome);
Ок, но в этой ветке это тоже должно быть отражено.

2021-03-18 05:32 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SensorEventQualifier.java
> +        if (event.getType() == LIGHT_ON || event.getType() == LIGHT_OFF) {
Повторюсь, должно быть отражено в этой ветке.

2021-03-18 05:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/DoorSensorEventHandler.java
> +    private final Collection<Room> rooms;
Должно быть отражено здесь.

2021-03-23 17:54 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/DoorSensorEventHandler.java
> +    private final Collection<Room> rooms;
Хорошо, исправил

2021-03-23 17:56 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/EventLoopProcessor.java
> +        EventProcessor eventProcessor = new EventProcessor(smartHome);
Хорошо, исправил.

2021-03-23 18:10 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/DoorSensorEventHandler.java
> +    private final Collection<Room> rooms;
Хорошо, исправил.

2021-03-24 05:34 UTC, a-ivanov requested changes

2021-03-24 05:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventProcessor.java
> +public class EventProcessor {
Перенесите сюда логику general event Handler, этот класс почти ничего не делает, кроме как запускает.

2021-03-24 05:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/GeneralSensorEventHandler.java
> +    private void setUpHandlers() {
Удалите и замените на передачу списка обработчиков через конструктор. DIP.

2021-03-24 05:34 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/DoorSensorEventHandler.java
> +        if (room.getName().equals("hall")) {
Добавьте в эту ветку обработчик сценария входной двери.

2021-03-24 12:19 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/SensorEventQualifier.java
> +        if (event.getType() == LIGHT_ON || event.getType() == LIGHT_OFF) {
Забыл написать, что исправил.

2021-03-24 12:24 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/DoorSensorEventHandler.java
> +        if (room.getName().equals("hall")) {
Хорошо, добавил.

2021-03-24 12:29 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/EventProcessor.java
> +public class EventProcessor {
Это противоречит комментарию ниже. Данный обработчик мне нужен, чтобы добавлять другие хендлеры и пригождается в последующих домашних заданиях.

2021-03-24 12:33 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/GeneralSensorEventHandler.java
> +    private void setUpHandlers() {
Хорошо, исправил.

2021-03-26 16:26 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventProcessor.java
> +public class EventProcessor {
Список с обработчиками должен быть создан в main, передан полем, не нарушая OCP и DIP. Зачем этот класс нужен? Вызывать один метод handle events? И не надо усложнять для будущих дз, в будущих дз и добавите нужный код. YAGNI + KISS.

2021-03-26 16:28 UTC, a-ivanov requested changes
Доделайте по замечаниям.

2021-03-29 13:04 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/EventProcessor.java
> +public class EventProcessor {
Хорошо, исправил.

2021-05-05 18:01 UTC, merged