Homework2
D1m0000n/smart-home-2021 pull request #2
Opened 2021-03-17 19:02 UTC by D1m0000n

2021-03-18 05:53 UTC, a-ivanov requested changes

2021-03-18 05:53 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
>      public Collection<Room> getRooms() {
Удалите, см. обсуждение в группе.

2021-03-18 05:53 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +        rooms.forEach(room -> room.doAction(action));
Можно ещё обработать сам дом.

2021-03-18 05:53 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/DoorSensorEventHandler.java
> +                if (room.getName().equals("hall")) {
По первому дз логику обработки сценария с дверью холла необходимо перенести в отдельный обработчик.

2021-03-23 18:34 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
>      public Collection<Room> getRooms() {
Хорошо, исправил.

2021-03-23 18:45 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/SmartHome.java
> +        rooms.forEach(room -> room.doAction(action));
Хорошо, исправил.

2021-03-23 19:13 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/DoorSensorEventHandler.java
> +                if (room.getName().equals("hall")) {
Хорошо, исправил.

2021-03-24 05:31 UTC, a-ivanov requested changes

2021-03-24 05:31 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/HallDoorSensorEventHandler.java
> +                if (room.getName().equals("hall")) {
Чтобы выполнить выключение света ещё необходимо сверить  id закрытой двери с входной.

2021-03-24 12:16 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/HallDoorSensorEventHandler.java
> +                if (room.getName().equals("hall")) {
Хорошо, исправил.

2021-03-26 16:33 UTC, a-ivanov requested changes

2021-03-26 16:33 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/HallDoorSensorEventHandler.java
> +                    smartHome.doAction(checkDoorId);
Здесь вы начинаете заново ходить по всем дверям и сверять ид независимо от имени комнаты. А надо найти комнату с именем "холл" и проверить, принадлежит ли закрытая дверь из события ей.

2021-03-26 18:13 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/HallDoorSensorEventHandler.java
> +                    smartHome.doAction(checkDoorId);
Хорошо, исправил.

2021-03-29 05:29 UTC, a-ivanov approved these changes

2021-05-05 18:09 UTC, merged