Homework3
D1m0000n/smart-home-2021 pull request #3
Opened 2021-03-24 12:14 UTC by D1m0000n

2021-03-26 06:02 UTC, a-ivanov reviewed
Создайте класс сигнализации, пенесите туда логику по переводу в разные состояния. Добавьте методы для проверки, что сигнализация включена. Используйте сигнализацию  в декораторе.

2021-03-26 06:02 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/states/AlarmState.java
> +    public void sendSMS() {
В отдельный класс, SRP.

2021-03-29 16:51 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/states/AlarmState.java
> +    public void sendSMS() {
Хорошо, исправил.

2021-03-31 16:42 UTC, a-ivanov requested changes

2021-03-31 16:42 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/Alarm.java
> +    private void deactivateActivatedAlarm(String code) {
Смысл шаблона состояние как раз в том, чтобы не было вот таких непонятных методов. Всё переходы должны выполняться в классах состояний. Перечитайте, как имплементировать этот паттерн.

2021-03-31 16:42 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +//    private final AlarmState alarmState;
Удалите закомментированный код.

2021-03-31 16:42 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +        this.alarm = new Alarm(smartHome, new SMSMessageSender());
Передавайте инстанс мессерджера через поле, DIP.

2021-03-31 16:42 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +        this.event = eventHandler.getEvent();
Не надо делать stateful поля, передавайте аргументом между private методами.

2021-03-31 18:39 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/Alarm.java
> +    private void deactivateActivatedAlarm(String code) {
Но вы же сами в комментарии выше указали, что логику по переводу в другие состояния нужно перенести в отдельный класс. Мне это тоже показалось странным, но я сделал так, как указано в комментарии

2021-04-01 05:55 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/Alarm.java
> +    private void deactivateActivatedAlarm(String code) {
Я имел в виду класс состояния. Если кажется странным, пишите, уточняйте в группе, прежде, чем делать пулл реквест. Пока, вроде, ни разу ещё вопросы в группе не оставались без внимания.

2021-04-06 22:01 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/Alarm.java
> +    private void deactivateActivatedAlarm(String code) {
Хорошо, исправил

2021-04-06 22:02 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +//    private final AlarmState alarmState;
Хорошо, исправил

2021-04-06 22:03 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +        this.alarm = new Alarm(smartHome, new SMSMessageSender());
Хорошо, исправил

2021-04-06 22:05 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +        this.event = eventHandler.getEvent();
Хорошо, исправил

2021-04-08 15:29 UTC, a-ivanov requested changes

2021-04-08 15:29 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/Alarm.java
> +        AlarmState alarmState = smartHome.getState();
Зачем состояние хранить  в доме, если оно является частью внутренней реализации сигнализации? Перечитайте шаблон состояние и переделайте. Не забудьте перенести логику переходов в классы состояния.

2021-04-08 15:29 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +        if (!isAlarmAction) {
Перепишите без stateful переменных в декораторе.

2021-04-08 15:29 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/Alarm.java
> +        return smartHome.getState().ignoreEvent;
Это вообще непонятно, что такое. Зачем каплить логику событий с сигнализацией? Уберите и решайте, продолжать ли обработку в декораторе.

2021-04-08 15:29 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/SensorEventHandlerDecorator.java
> +public class SensorEventHandlerDecorator implements SensorEventHandler {
Вот какой смысл этого класса? Вызвать метод другого класса? Ещё и специализированного, не интерфейса, нарушая DIP? Удалите.

2021-04-14 12:00 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +        if (!isAlarmAction) {
Хорошо, исправил.

2021-04-14 12:00 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/Alarm.java
> +        AlarmState alarmState = smartHome.getState();
Хорошо, исправил.

2021-04-14 12:00 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/Alarm.java
> +        return smartHome.getState().ignoreEvent;
Хорошо, исправил.

2021-04-14 12:03 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/SensorEventHandlerDecorator.java
> +public class SensorEventHandlerDecorator implements SensorEventHandler {
Хорошо, исправил.

2021-04-16 05:57 UTC, a-ivanov requested changes

2021-04-16 05:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/Alarm.java
> +    public void setAlarmState(AlarmState state) {
Pqlackage private, инкапсуляция, обсуждали в группе.

2021-04-16 05:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/GeneralSensorEventHandler.java
> +        handlers.add(new LightSensorEventHandler(smartHome));
Нарушение DIP, исправьте.

2021-04-16 05:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +            if (!ignoreEvent(alarm.getAlarmState())) {
Удалите getState, перепишите, как обсуждали в группе.

2021-04-16 05:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/states/AlarmState.java
> +    public void sendMessage() {
Нарушение SRP, исправьте.

2021-04-16 05:57 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/EventProcessor.java
> +        SensorEventHandler sensorEventHandler = new AlarmSensorEventDecorator(smartHome, new GeneralSensorEventHandler(smartHome));
Нарушение DIP, исправьте.

2021-04-16 16:09 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/GeneralSensorEventHandler.java
> +        handlers.add(new LightSensorEventHandler(smartHome));
Хорошо, исправил

2021-04-16 16:11 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/states/AlarmState.java
> +    public void sendMessage() {
Хорошо, исправил

2021-04-16 16:14 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/EventProcessor.java
> +        SensorEventHandler sensorEventHandler = new AlarmSensorEventDecorator(smartHome, new GeneralSensorEventHandler(smartHome));
Хорошо, исправил

2021-04-16 16:18 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +            if (!ignoreEvent(alarm.getAlarmState())) {
Мне этот метод и не нужен, я используется только для тестов

2021-04-16 16:18 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +            if (!ignoreEvent(alarm.getAlarmState())) {
Могу удалить в принципе вместе с соответствующими тестами

2021-04-16 16:24 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +            if (!ignoreEvent(alarm.getAlarmState())) {
getState оставил только для тестов. Логику дома переписал так, чтобы она getState не использовала. В принципе могу удалить getState вместе с соответствующими тестами

2021-04-16 16:45 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/Alarm.java
> +    public void setAlarmState(AlarmState state) {
Хорошо, исправил

2021-04-20 13:24 UTC, a-ivanov requested changes

2021-04-20 13:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/Alarm.java
> +    public AlarmState getAlarmState() {
private, инкапсуляция

2021-04-20 13:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/Alarm.java
> +    public boolean ignoreEvent() {
Вводящее в заблуждение название, ignore с чьей точки зрения? С точки зрения сигнализации, это просто ответ на вопрос, isAlerted.

2021-04-20 13:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +        MessageSender sender = new SMSMessageSender();
DIP, передавайте через аргумент конструктора.

2021-04-20 13:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +    public void handleEvent(SensorEvent event) {
`@Override` аннотация

2021-04-20 13:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +        this.alarm = new Alarm(smartHome, sender);
DIP, передавайте через аргумент конструктора.

2021-04-20 13:24 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/handlers/GeneralSensorEventHandler.java
> +public class GeneralSensorEventHandler implements SensorEventHandler {
CompositeSensorEventHandler

2021-04-21 22:05 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/Alarm.java
> +    public boolean ignoreEvent() {
Хорошо, исправил.

2021-04-21 22:06 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/Alarm.java
> +    public AlarmState getAlarmState() {
Писал выше, что данный метод используется только для тестов

2021-04-21 22:08 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +        MessageSender sender = new SMSMessageSender();
Хорошо, исправил

2021-04-21 22:08 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +    public void handleEvent(SensorEvent event) {
Хорошо, добавил.

2021-04-21 22:11 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/decorators/AlarmSensorEventDecorator.java
> +        this.alarm = new Alarm(smartHome, sender);
Хорошо, исправил

2021-04-21 22:13 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/handlers/GeneralSensorEventHandler.java
> +public class GeneralSensorEventHandler implements SensorEventHandler {
Хорошо, исправил

2021-04-22 07:04 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/Alarm.java
> +    public AlarmState getAlarmState() {
Тогда этого метода не должно вообще бытьмздесь, в коде с бизнес логикой. Только для теста методы не надо создавать, придумайте другую стратегию дл ятестирования. Тестирование проверяет не внутреннюю реализацию, а публичное API, вам не обязательно убеждаться, что было сменено состояние

2021-04-22 07:15 UTC, a-ivanov requested changes
Удалите  getState в сигнализации

2021-04-22 18:14 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/sensors/alarm/Alarm.java
> +    public AlarmState getAlarmState() {
Хорошо, исправил

2021-04-26 16:50 UTC, D1m0000n commented
> Удалите getState в сигнализации

Хорошо, исправил.

2021-04-27 06:51 UTC, a-ivanov approved these changes

2021-05-05 18:11 UTC, merged