Homework4
D1m0000n/smart-home-2021 pull request #4
Opened 2021-03-29 19:50 UTC by D1m0000n

2021-04-02 05:21 UTC, a-ivanov requested changes

2021-04-02 05:21 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/adapters/SmartHomeAdapter.java
> +    private SensorEventType transformCCSensorEventTypeToSensorEventType(String CCEventType) {
Сделайте мапу, перенесите в конфигурацию бином.

2021-04-07 16:48 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/adapters/SmartHomeAdapter.java
> +    private SensorEventType transformCCSensorEventTypeToSensorEventType(String CCEventType) {
Хорошо, исправил

2021-04-09 16:16 UTC, a-ivanov approved these changes

2021-04-09 16:16 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/adapters/SmartHomeAdapter.java
> +        return transformEvents.get(CCEventType);
Проверка на null

2021-05-05 18:12 UTC, merged