Homework5
D1m0000n/smart-home-2021 pull request #5
Opened 2021-04-07 20:52 UTC by D1m0000n

2021-04-16 06:49 UTC, a-ivanov requested changes
См. Обсуждение в группе, создайте необходимые бины.

2021-04-16 06:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/remoteControllers/RemoteController.java
> +        Command command = codeToCommand.get(buttonCode);
Проверка на null

2021-04-16 06:49 UTC, a-ivanov commented on src/main/java/ru/sbt/mipt/oop/remoteControllers/commands/Command.java
> +    protected final SmartHome smartHome;
Ну вот опять, зачем класс ради только одного поля? В классе должна быть какая-то общая логика, чтобы ограничения его контракта имели смысл. Иначе лучше использовать интерфейс.

2021-04-21 22:19 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/remoteControllers/RemoteController.java
> +        Command command = codeToCommand.get(buttonCode);
Хорошо, исправил

2021-04-21 22:23 UTC, D1m0000n commented on src/main/java/ru/sbt/mipt/oop/remoteControllers/commands/Command.java
> +    protected final SmartHome smartHome;
Хорошо, исправил

2021-04-22 07:19 UTC, a-ivanov approved these changes

2021-05-05 18:12 UTC, merged